[package]
name = "cha"
version = "0.1.0"
authors = ["betta <betta0801@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
indicatif = "0.11.0"
log = "0.4.8"
env_logger = "0.6.2"
